<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="css/normalize.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <title>Evolve: Revive your natural state</title>
</head>
<body>
    <header class="header">
       <div class="header-top">
            <div class="header-top-left">
                <a href="index.phtml"><i class="fas fa-torii-gate"></i></a>
            </div>
            <div class="header-top-center">
                <a href="index.phtml">Evolve</a>
            </div>
            <div class="header-top-right">
                <a href="#"><i class="fas fa-user"></i></a>
                <a href="#"><i class="fas fa-cart-arrow-down"></i></a>
            </div>
        </div>
        
        <nav class="nav">
            <a href="products.phtml">Compléments</a>
            <a href="equipment.phtml">Equipements</a>
            <a href="accessories.phtml">Accessoires</a>
        </nav>
    </header>
    
    
    <main>
        <main>
        <div class="main-background">
            <div class="container-other">
                 <article class="item-list">
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/accessories/accessories 1.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Casque audio sportif</h3></a>
                             <p>Un casque antitranspirant customisé pour vos séances</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/accessories/Accessories 2.jpeg"></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Bandes de soutien & Ceinture de force</h3></a>
                             <p>Le renfort nécessaire</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/accessories/accessories 3.jpeg"></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Bande Élastique</h3></a>
                             <p>Pour vos exercices d'assouplissement</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/accessories/accessories 4.jpeg"></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Corde à sauter Boxing</h3></a>
                             <p>Pour un cardio de qualité</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/accessories/accessories tapis.jpeg"></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Tapis de gym</h3></a>
                             <p>Votre partenaire de fin de séance</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/accessories/accessories 6.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Bandes de poignets</h3></a>
                             <p>Protégez vos poignets et progressez</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                 </article>   
            </div>
        </div>
        
        
        
        
    </main>
    
    
    <footer>
       <div class="footer">
            <section class="section-footer">
                <h2 class="footer-logo">Evolve</h2>
                <ul>
                    <a href="about.phtml"><li>À propos de nous</li></a>
                    <li>Evolve Gym</li>
                    <li>Evolve Center</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Contact</h2>
                <ul>
                    <li>FAQ</li>
                    <li>Contact Email</li>
                    <li>Effectuer un retour</li>
                    <li>Guide des tailles</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Mon compte</h2>
                <ul>
                    <li>Connexion</li>
                    <li>Créer un compte</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Réseaux Sociaux</h2>
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </section>
        </div> 
        
        
    </footer>
    <script src="js/script.js"></script>
</body>
</html>