<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="css/normalize.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <title>Evolve: Revive your natural state</title>
</head>
<body>
    <header class="header">
       <div class="header-top" id="header-top" class="nav-position-support">
            <div class="header-top-left">
                <a href="index.phtml"><i class="fas fa-torii-gate"></i></a>
            </div>
            <div class="header-top-center">
                <a href="index.phtml">Evolve</a>
            </div>
            <div class="header-top-right">
                <div class="header-top-right-a">
                    <a href="#"><i class="fas fa-user"></i></a>
                </div>
                <div class="header-top-right-b">
                    <a href="#"><i class="fas fa-cart-arrow-down"></i></a>
                </div>
            </div>
        </div>
        
        <div id="nav-position" class="nav-position">
            <nav class="nav">
                <a class="nav-a" href="products.phtml">Compléments</a>
                <div class="dropdown">
                    <a class="nav-a" href="equipment.phtml">Equipements</a>
                    <div class="dropdown-content">
                        <a href="men.phtml">Homme</a>
                        <a href="women.phtml">Femme</a>
                    </div>
                </div>
                <a class="nav-a" href="accessories.phtml">Accessoires</a>
            </nav>
        </div>
    </header>

    <main>
        <section class="main-about">
            <div class="video-container">
                <video autoplay loop id="main-video">
                    <source src="video/main_video.mp4" type="video/mp4" playsinline="playsinline">
                    <!-- Ce paragraphe ne s'affichera que dans le cas où le navigateur
                     ne sait pas interpréter la balise vidéo -->
                    <p class="alert">
                    Votre navigateur ne supporte pas la balise vidéo. Veuillez mettre à jour votre navigateur.
                    </p>
                </video>
            </div>
            <div class="main-video-title">
                <h1 class="main-about-title">Ranimez vos instincts</h1>
                <!--<a class="btn-about" href="about.phtml">En savoir plus</a>-->
            </div>
        </section>
        
        <div class="main-background">
            <div class="container-main" class="container-main2">
                <section class="main-products">
                    <article class="products-intro">
                        <div class="intro-items">
                            <h2>Nutrition</h2>
                            <a href="products.phtml">Explorer</a>
                        </div>
                        <div class="img-container-main">
                            <a href="products.phtml"><img src="img/isolat.png" alt="nutrition"></a>
                        </div>
                    </article>
                </section>
                
                
                <section class="main-select">
                    <article class="main-title">
                        <h2>Nos meilleures ventes</h2>
                    </article>
                
                    <section class="selections">
                        <article class="select-item">
                            <div class="img-container-select">
                                <a href="product.phtml"><img src="img/products/product 5.png" alt="isolat de whey"></a>
                            </div>
                            <a href="product.phtml"><h4 class="select-item-title">Isolat de Nouvelle-Zélande</h4></a>
                            <a href="product.phtml"><p>Notre Isolat de Whey Bio</p></a>
                            <a href="product.phtml"><p class="price">95,00€ EUR</p></a>
                        </article>
                        <article class="select-item">
                            <div class="img-container-select">
                                <img src="img/booster.jpg" alt="booster">
                            </div>
                            <h4 class="select-item-title">Le Boost</h4>
                            <p>Notre Pre-Workout</p>
                            <p class="price-out">Rupture de stock</p>
                        </article>
                        <article class="select-item">
                            <div class="img-container-select">
                                <img src="img/bcaa.png" alt="BCAA">
                            </div>
                            <h4 class="select-item-title">Pur BCAA</h4>
                            <p>L'énergie pour l'entrainement</p>
                            <p class="price-out">Rupture de stock</p>
                        </article>
                    </section>
                </section>
               
                
                <section class="main-models">
                    <article class="main-model-item">
                        <div class="img-container-model">
                            <a href="equipment.phtml"><img src="img/man.png" alt="mannequin homme"></a>
                        </div>
                        <div class="main-model-intro">
                            <h2>Équipements</h2>
                            <a href="equipment.phtml">Explorer</a>
                        </div>
                    </article>
                    <article class="main-model-item">
                        <div class="img-container-model">
                            <a href="women.phtml"><img src="img/woman.png" alt="mannequin femme"></a>
                        </div>
                        <div class="main-model-intro">
                            <h2>Femme</h2>
                            <a href="women.phtml">Explorer</a>
                        </div>
                    </article>
                    <article class="main-model-item">
                        <div class="img-container-model">
                            <a href="men.phtml"><img src="img/model.png" alt="mannequin homme"></a>
                        </div>
                        <div class="main-model-intro">
                            <h2>Homme</h2>
                            <a href="men.phtml">Explorer</a>
                        </div>
                    </article>
                </section>
            </div>
        </div>
    </main>
    
    
    <footer>
        <div class="footer">
            <section class="section-footer">
                <h2 class="footer-logo">Evolve</h2>
                <ul>
                    <a href="about.phtml"><li>À propos de nous</li></a>
                    <li>Evolve Gym</li>
                    <li>Evolve Center</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Contact</h2>
                <ul>
                    <li>FAQ</li>
                    <li>Contact Email</li>
                    <li>Effectuer un retour</li>
                    <li>Guide des tailles</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Mon compte</h2>
                <ul>
                    <li>Connexion</li>
                    <li>Créer un compte</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Réseaux Sociaux</h2>
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </section>
        </div>
    </footer>
    
    
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="js/script.js"></script>
</body>
</html>