<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="css/normalize.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <title>Evolve: Revive your natural state</title>
</head>
<body>
    <header class="header">
       <div class="header-top">
            <div class="header-top-left">
                <a href="index.phtml"><i class="fas fa-torii-gate"></i></a>
            </div>
            <div class="header-top-center">
                <a href="index.phtml">Evolve</a>
            </div>
            <div class="header-top-right">
                <a href="#"><i class="fas fa-user"></i></a>
                <a href="#"><i class="fas fa-cart-arrow-down"></i></a>
            </div>
        </div>
        
        <nav class="nav">
            <a href="products.phtml">Compléments</a>
            <a href="equipment.phtml">Equipements</a>
            <a href="accessories.phtml">Accessoires</a>
        </nav>
    </header>


    <main>
        <div class="main-background">
            <div class="container-other">
                 <article class="select-product">
                     <div class="item-logo">
                        <p>Evolve</p>
                     </div>
                     <div class="img-product-container">
                        <img src="img/male/men 5.jpeg"> 
                     </div>
                     <div class="select-product-details">
                        <h1>Tshirt Tech</h1>
                        <div class="details-price">
                            <p>Le prix inclut la TVA</p>
                            <strong>25,00€ EUR</strong>
                        </div>
                        <p><strong>Couleur:</strong>Bordeaux</p>
                        <form class="details-quantity">
                             <legend><strong>Taille</strong></legend>
                             <select>
                                 <option>S</option>
                                 <option>M</option>
                                 <option>L</option>
                                 <option>XL</option>
                                 <option>XXL</option>
                             </select>
                        </form>
                        <input class="details-cta" type="submit" value="Ajouter au panier">
                        <div class="details-description">
                            <h2>Description</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi iure, voluptates aliquam eos qui molestiae quae exercitationem blanditiis unde, temporibus architecto provident iusto dolor eaque assumenda, distinctio iste. Unde totam dicta reiciendis et, voluptas quidem adipisci quam tempora quas cumque eos dolore. Impedit molestias itaque, blanditiis consequuntur qui velit voluptas, rerum repellat doloribus recusandae dicta omnis ipsam laudantium, dolor aliquam.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro unde sequi quo necessitatibus sint repudiandae pariatur rerum consectetur consequatur quod. Vero accusantium officiis corrupti dolor vitae quia ad rem aliquid dolore, itaque optio consequuntur ipsam.</p>
                        </div>
                     </div>
                 </article>   
            </div>
        </div>
        
        
        
        
        
        
        
        
    </main>
    
    
    <footer>
        <div class="footer">
            <section class="section-footer">
                <h2 class="footer-logo">Evolve</h2>
                <ul>
                    <a href="about.phtml"><li>À propos de nous</li></a>
                    <li>Evolve Gym</li>
                    <li>Evolve Center</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Contact</h2>
                <ul>
                    <li>FAQ</li>
                    <li>Contact Email</li>
                    <li>Effectuer un retour</li>
                    <li>Guide des tailles</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Mon compte</h2>
                <ul>
                    <li>Connexion</li>
                    <li>Créer un compte</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Réseaux Sociaux</h2>
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </section>
        </div>
        
        
    </footer>
    <script src="js/script.js"></script>
</body>
</html>