<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="css/normalize.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <title>Evolve: Revive your natural state</title>
</head>
<body>
    <header class="header">
       <div class="header-top">
            <div class="header-top-left">
                <a href="index.phtml"><i class="fas fa-torii-gate"></i></a>
            </div>
            <div class="header-top-center">
                <a href="index.phtml">Evolve</a>
            </div>
            <div class="header-top-right">
                <a href="#"><i class="fas fa-user"></i></a>
                <a href="#"><i class="fas fa-cart-arrow-down"></i></a>
            </div>
        </div>
        
        <nav class="nav">
            <a href="products.phtml">Compléments</a>
            <a href="equipment.phtml">Equipements</a>
            <a href="accessories.phtml">Accessoires</a>
        </nav>
    </header>
    
    
    <main>
        <main>
        <div class="main-background">
            <div class="container-other">
                 <article class="item-list">
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/female/woman 1.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Look Brassière et Leggings</h3></a>
                             <p>Pour un maintien et une liberté de mouvement</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/female/woman 2.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Look Brassière et short</h3></a>
                             <p>Vous fournira la performance nécessaire</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/female/woman 3.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Brassière et Leggings Evolve</h3></a>
                             <p>Pour un maintien et une liberté de mouvement</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/female/woman 4.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Look Brassière et Leggings</h3></a>
                             <p>Pour un maintien et une liberté de mouvement</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/female/woman 5.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Look Brassière et Leggings</h3></a>
                             <p>Pour un maintien et une liberté de mouvement</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                     <div class="item-container">
                         <div class="img-item-container">
                             <a href="#"><img src="img/female/woman 6.jpeg" ></a>
                         </div>
                         <div class="item-container-text">
                             <a href="#"><h3>Look Brassière et Leggings</h3></a>
                             <p>Pour un maintien et une liberté de mouvement</p>
                             <a href=# class="price-out">Rupture de stock</a>
                         </div>
                     </div>
                 </article>   
            </div>
        </div>
        
        
        
        
    </main>
    
    
    <footer>
        <div class="footer">
            <section class="section-footer">
                <h2 class="footer-logo">Evolve</h2>
                <ul>
                    <a href="about.phtml"><li>À propos de nous</li></a>
                    <li>Evolve Gym</li>
                    <li>Evolve Center</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Contact</h2>
                <ul>
                    <li>FAQ</li>
                    <li>Contact Email</li>
                    <li>Effectuer un retour</li>
                    <li>Guide des tailles</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Mon compte</h2>
                <ul>
                    <li>Connexion</li>
                    <li>Créer un compte</li>
                </ul>
            </section>
            <section class="section-footer">
                <h2 class="footer-title">Réseaux Sociaux</h2>
                <a href="#"><i class="fab fa-facebook"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
            </section>
        </div>
        
        
    </footer>
    <script src="js/script.js"></script>
</body>
</html>